version: '3.3'

services:
  bot:
    restart: on-failure
    env_file:
      - ".env.dist"
    build:
      context: .
    networks:
      - db_network
    depends_on:
      - postgres
    volumes:
      - ${WORK_DIR:-.}/scripts:/scripts
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB_FSM:
      REDIS_DB_JOBSTORE:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD:
      POSTGRES_USER:
      POSTGRES_DB:

  postgres:
    image: postgres:12.8-alpine
    restart: on-failure
    networks:
      - db_network
    expose:
      - 5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER:
      POSTGRES_DB:

networks:
  db_network:
    driver: bridge


volumes:
  postgres-data: